---
- name: Load OS-specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install LMDB packages
  apt:
    name: "{{ lmdb_packages }}"
    state: present
    update_cache: yes
